### ISSUE TITLE
link metadata for manifest has invalid crossorigin attribute value 

### ISSUE THREAD

**Issue by boycott** [alextim/astro-lib#12]
using version **0.3.1** of astro-webmanifest

with **astro.config.mjs** integration settings:
  webmanifest({
      icon: <redacted>,
      name: <redacted>,
      short_name: <redacted>,
      description: <redacted>,
      start_url: '/',
      theme_color: '#101726',
      background_color: '#101726',
      display: 'standalone'
  })

upon `npm run build`

astro generated pages contain `<link rel="manifest" href="/manifest.webmanifest" crossorigin="anonymus">`

issue:  "anonymus" should be "anonymous".

feature request: is this possible to add as a setting change like 
`{ crossorigin: 'anonymous' || 'use-credentials' } ?

**Comment by alextim** [comment]
Thanks for your issue. I will fix.

About feature request: crossorigin option already has a type CrossOrigin = 'anonymous' | 'use-credentials';
And it's validated against schema.
