### ISSUE TITLE
robots-txt: extend host to support boolean value (automatic resolving)

### ISSUE THREAD

**Issue by edv-ns** [alextim/astro-lib#36]
## Context

Following the pattern of how **sitemap** option is done, the host could also be resolved automatically from the Astro config `site` value, so it could be both boolean or string(s):

**sitemap**
Type | Required | Default value
-- | -- | --
`Boolean` / `String` / `String[]` | No | `true`

As I have checked both inspiration packages accepts `sitemap` as string ([gatsby-plugin-robots#options](https://github.com/mdreizin/gatsby-plugin-robots-txt#options) and [generate-robotstxt](https://github.com/itgalaxy/generate-robotstxt/blob/master/src/standalone.js#L187)) and leaves consumer responsible for the values they pass, but `astro-robots-txt` package targets Astro framework, so it does automatic `sitemap` resolving which is smart. Why couldn't it do the same for `host` value?

## Proposed change

**host**
Type | Required | Default value
-- | -- | --
`Boolean` / `String` | No | `undefined`

Having that in mind, available `host` types would be `Boolean` or  `String` and reflect the following flows:
  - `host: undefined` -> default (same as is now, host is omitted)
  - `host: true` -> would resolve host automatically via Astro site prop and will include it into sitemap
  - `host: 'any-string-value.com'` -> would print out the custom value (as it works now)
  
 ## TODO
 - Make `host` prop be available as `Boolean` / `String`

**Comment by alextim** [comment]
Thanks for the issue.
Your idea looks not bad. I'll do.

**Comment by edv-ns** [comment]
@alextim Awesome! Thanks for quick reply and improvement 🙏 We can close this task as done.
