### ISSUE TITLE
"createLinkInHead: false" still adding sitemap link to head of all html pages.

### ISSUE THREAD

**Issue by saurabhck12** [alextim/astro-lib#46]
I'm generating a sitemap with advanced config. I made createLinkInHead: false still it is adding sitemap-index.xml to head of every page. What would be the fix?

`11:04:32 [build] Waiting for the astro-sitemap integration...
astro-sitemap: Sitemap links are inserted into <head> section of generated pages (17768 of 17768).`

Thanks

**Comment by alextim** [comment]
Thanks for the issue. I'll ivestigate tomorrow.

**Comment by alextim** [comment]
Hello!
v0.5.0 just released. 
You may play online the [advanced example](https://stackblitz.com/fork/github/alextim/astro-lib/tree/main/examples/sitemap/advanced) with the `createLinkInHead` option set to `false`.
Hope it solved.
